---
title: "Stretch01"
author: "Ming & Huixin"
format: html
editor: source
self-contained: true
---
## Graph 1
Line chart： Virginia's labor force and total population over years
```{r}
#| output: false
library(readr)
library(tidyverse)
data <- read_csv("Virginia_Employment_Status_of_the_Population_by_Sex_by_Race_and_by_Age_by_Year.csv")

```

```{r}
data %>%
  filter(PopulationGroup == "Total") %>%
  ggplot() +
  geom_line(aes(x = Year,
                y = CivilianLaborForce,
                color = "Labor force")) +
  geom_line(aes(x = Year,
                y = CivilianNonInstitutionalPopulation,
                color = "Population")) +
  scale_color_manual("", 
                     values = c(
    "Labor force" = "red",
    "Population" = "blue")) +
  labs(y = "The number of people (thousand)",
       title = "Difference Between Labor Force and Population",
       subtitle = "The increase of labor force fluctuates, while total population increases steadily in Virginia.",
       caption = "Source: data.virginia.gov")

```
